language: android
jdk: oraclejdk7
branches:
  only:
    - develop
    - master
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
before_install:
 - chmod +x gradlew
android:
  components:
    - android-22
    - build-tools-22.0.1
  licenses:
    - android-sdk-license-5be876d5
script: ./gradlew assembleDebug
